from tkinter import *

ttt=Tk()
ttt.config(background='white')
b1=Button(ttt,height=4,width=10,bd=2,bg='white',relief='groove')
b2=Button(ttt,height=4,width=10,bd=2,bg='white',relief='groove')
b3=Button(ttt,height=4,width=10,bd=2,bg='white',relief='groove')
b4=Button(ttt,height=4,width=10,bd=2,bg='white',relief='groove')
b5=Button(ttt,height=4,width=10,bd=2,bg='white',relief='groove')
b6=Button(ttt,height=4,width=10,bd=2,bg='white',relief='groove')
b7=Button(ttt,height=4,width=10,bd=2,bg='white',relief='groove')
b8=Button(ttt,height=4,width=10,bd=2,bg='white',relief='groove')
b9=Button(ttt,height=4,width=10,bd=2,bg='white',relief='groove')
reset=Button(ttt,text='Reset',bd=2,bg='white',relief='groove',fg='blue')
close=Button(ttt,text='Close',bd=2,bg='white',relief='groove',fg='red',command=ttt.destroy)

b1.grid(row=0,column=0)
b2.grid(row=0,column=1)
b3.grid(row=0,column=2)
b4.grid(row=1,column=0)
b5.grid(row=1,column=1)
b6.grid(row=1,column=2)
b7.grid(row=2,column=0)
b8.grid(row=2,column=1)
b9.grid(row=2,column=2)
close.grid(row=3,column=2)
reset.grid(row=3,column=0)

ttt.mainloop()